DATA_PATH="/home/ubuntu/data"
CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE="/home/ubuntu/klue/data/kwok-provider-templates.yaml"
EMULATION_PREFIX="CHANGE_ME"
SPEED_UP_FACTOR=2
SPOT_LIFETIME_PATH="/home/ubuntu/klue/data/aws_spot_preemption_data.csv"
NODE_INTERRUPTION_INTERVAL=300
INTERRUPTION_RANDOM_SEED=42

EMULATION_NAME="${EMULATION_PREFIX}-simple"
RULE_PATH=""
./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RULE_PATH"
