DATA_PATH="/home/ubuntu/test_data"
CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE="/home/ubuntu/klue/data/kwok-provider-templates.yaml"
EMULATION_PREFIX="test"
SPEED_UP_FACTOR=2
SPOT_LIFETIME_PATH=0
NODE_INTERRUPTION_INTERVAL=3600
INTERRUPTION_RANDOM_SEED=42

EMULATION_NAME="${EMULATION_PREFIX}-simple"
RULE_PATH="/home/ubuntu/klue/data/allocation_rules/reliability.json"
RELIABILITY_SCHEDULER="reliability-scheduler-on"
./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RELIABILITY_SCHEDULER" "$RULE_PATH"
