DATA_PATH="/home/ubuntu/seven_days_input_filter"
CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE="/home/ubuntu/klue/data/kwok-provider-templates.yaml"
EMULATION_PREFIX="seven-days"
SPEED_UP_FACTOR=2
SPOT_LIFETIME_PATH=0
NODE_INTERRUPTION_INTERVAL=3600
INTERRUPTION_RANDOM_SEED=42
# OPEN_STACK_CONTAINER="mestrado-caetano-resultados"
# OPEN_STACK_CONTAINER_PATH="one_day_spot_5_min_interruption"


#EMULATION_NAME="${EMULATION_PREFIX}-reliability-scheduler-0_5"
#RULE_PATH="/home/ubuntu/klue/data/allocation_rules/reliability_5.json"
#RELIABILITY_SCHEDULER="reliability-scheduler-on"
#./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RELIABILITY_SCHEDULER" "$RULE_PATH"

#EMULATION_NAME="${EMULATION_PREFIX}-reliability-scheduler-0_55"
#RULE_PATH="/home/ubuntu/klue/data/allocation_rules/reliability_55.json"
#RELIABILITY_SCHEDULER="reliability-scheduler-on"
#./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RELIABILITY_SCHEDULER" "$RULE_PATH"

#EMULATION_NAME="${EMULATION_PREFIX}-reliability-scheduler-0_6"
#RULE_PATH="/home/ubuntu/klue/data/allocation_rules/reliability_6.json"
#RELIABILITY_SCHEDULER="reliability-scheduler-on"
#./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RELIABILITY_SCHEDULER" "$RULE_PATH"

#EMULATION_NAME="${EMULATION_PREFIX}-reliability-scheduler-0_65"
#RULE_PATH="/home/ubuntu/klue/data/allocation_rules/reliability_65.json"
#RELIABILITY_SCHEDULER="reliability-scheduler-on"
#./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RELIABILITY_SCHEDULER" "$RULE_PATH"

#EMULATION_NAME="${EMULATION_PREFIX}-reliability-scheduler-0_71"
#RULE_PATH="/home/ubuntu/klue/data/allocation_rules/reliability_71.json"
#RELIABILITY_SCHEDULER="reliability-scheduler-on"
#./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RELIABILITY_SCHEDULER" "$RULE_PATH"

#EMULATION_NAME="${EMULATION_PREFIX}-reliability-scheduler-0_72"
#RULE_PATH="/home/ubuntu/klue/data/allocation_rules/reliability_72.json"
#RELIABILITY_SCHEDULER="reliability-scheduler-on"
#./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RELIABILITY_SCHEDULER" "$RULE_PATH"

#EMULATION_NAME="${EMULATION_PREFIX}-reliability-scheduler-0_73"
#RULE_PATH="/home/ubuntu/klue/data/allocation_rules/reliability_73.json"
#RELIABILITY_SCHEDULER="reliability-scheduler-on"
#./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RELIABILITY_SCHEDULER" "$RULE_PATH"

#EMULATION_NAME="${EMULATION_PREFIX}-reliability-scheduler-0_74"
#RULE_PATH="/home/ubuntu/klue/data/allocation_rules/reliability_74.json"
#RELIABILITY_SCHEDULER="reliability-scheduler-on"
#./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RELIABILITY_SCHEDULER" "$RULE_PATH"

#EMULATION_NAME="${EMULATION_PREFIX}-reliability-scheduler-0_7"
#RULE_PATH="/home/ubuntu/klue/data/allocation_rules/reliability_7.json"
#RELIABILITY_SCHEDULER="reliability-scheduler-on"
#./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RELIABILITY_SCHEDULER" "$RULE_PATH"

#EMULATION_NAME="${EMULATION_PREFIX}-reliability-scheduler-0_75"
#RULE_PATH="/home/ubuntu/klue/data/allocation_rules/reliability_75.json"
#RELIABILITY_SCHEDULER="reliability-scheduler-on"
#./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RELIABILITY_SCHEDULER" "$RULE_PATH"

#EMULATION_NAME="${EMULATION_PREFIX}-reliability-scheduler-0_85"
#RULE_PATH="/home/ubuntu/klue/data/allocation_rules/reliability_85.json"
#RELIABILITY_SCHEDULER="reliability-scheduler-on"
#./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RELIABILITY_SCHEDULER" "$RULE_PATH"

#EMULATION_NAME="${EMULATION_PREFIX}-reliability-scheduler-0_95"
#RULE_PATH="/home/ubuntu/klue/data/allocation_rules/reliability_95.json"
#RELIABILITY_SCHEDULER="reliability-scheduler-on"
#./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RELIABILITY_SCHEDULER" "$RULE_PATH"


RELIABILITY_SCHEDULER="reliability-scheduler-off"


EMULATION_NAME="${EMULATION_PREFIX}-simple"
RULE_PATH=""
./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RULE_PATH"

#EMULATION_NAME="${EMULATION_PREFIX}-anti-affinity-required"
#RULE_PATH="/home/ubuntu/klue/data/allocation_rules/anti_affinity_required.json"
#./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RULE_PATH"

#EMULATION_NAME="${EMULATION_PREFIX}-anti-affinity-preferred"
#RULE_PATH="/home/ubuntu/klue/data/allocation_rules/anti_affinity_preferred.json"
#./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RULE_PATH"

# EMULATION_NAME="${EMULATION_PREFIX}-topology-spread-required-1"
# RULE_PATH="/home/ubuntu/klue/data/allocation_rules/topology_spread_required.json"
# ./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RULE_PATH"

# EMULATION_NAME="${EMULATION_PREFIX}-topology-spread-preferred-1"
# RULE_PATH="/home/ubuntu/klue/data/allocation_rules/topology_spread_preferred.json"
# ./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RULE_PATH"

# EMULATION_NAME="${EMULATION_PREFIX}-topology-spread-required-2"
# RULE_PATH="/home/ubuntu/klue/data/allocation_rules/topology_spread_required_2.json"
# ./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RULE_PATH"

# EMULATION_NAME="${EMULATION_PREFIX}-topology-spread-preferred-2"
# RULE_PATH="/home/ubuntu/klue/data/allocation_rules/topology_spread_preferred_2.json"
# ./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RULE_PATH"

#EMULATION_NAME="${EMULATION_PREFIX}-topology-spread-required-3"
#RULE_PATH="/home/ubuntu/klue/data/allocation_rules/topology_spread_required_3.json"
#./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RULE_PATH"

#EMULATION_NAME="${EMULATION_PREFIX}-topology-spread-preferred-3"
#RULE_PATH="/home/ubuntu/klue/data/allocation_rules/topology_spread_preferred_3.json"
#./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RULE_PATH"

#EMULATION_NAME="${EMULATION_PREFIX}-topology-spread-required-10"
#RULE_PATH="/home/ubuntu/klue/data/allocation_rules/topology_spread_required_10.json"
#./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RELIABILITY_SCHEDULER" "$RULE_PATH"

#EMULATION_NAME="${EMULATION_PREFIX}-topology-spread-preferred-10"
#RULE_PATH="/home/ubuntu/klue/data/allocation_rules/topology_spread_preferred_10.json"
#./run.sh "$DATA_PATH" "$CLUSTER_AUTOSCALER_PROVIDER_TEMPLATE" "$EMULATION_NAME" "$SPEED_UP_FACTOR" "$SPOT_LIFETIME_PATH" "$NODE_INTERRUPTION_INTERVAL" "$INTERRUPTION_RANDOM_SEED" "$RELIABILITY_SCHEDULER" "$RULE_PATH"
